Laysa part 01
marimeireles/tutorial pull request #10
Opened 2021-10-04 15:52 UTC by laysauchoa

@marimeireles 

nao entendi essa parte:

> Uma última adição está no próprio ipywidgets: o novo widgetOutput pode exibir qualquer conteúdo que pode ser renderizado em um Jupyter notebook. Isso significa que qualquer coisa que você pode mostrar em um notebook, pode incluir em um widget usando apenas Python.

2021-10-11 17:47 UTC, marimeireles requested changes
Thank youuu

2021-10-11 17:47 UTC, marimeireles commented on notebooks/01.00-overview.ipynb
> +    "O que você pode fazer usando apenas Python cresceu bastante nos últimos anos, à medida que ferramentas mais sofisticadas que se conectam ao ecossistema de widgets do Jupyter foram sendo escritas
aumentou bastante

2021-10-12 07:45 UTC, laysauchoa commented
@marimeireles poderia olhar essa duvida que eu tive se vc souber? coloque na descrição no pr, obrigada :D

2021-10-12 07:47 UTC, laysauchoa commented on notebooks/01.00-overview.ipynb
> +    "O que você pode fazer usando apenas Python cresceu bastante nos últimos anos, à medida que ferramentas mais sofisticadas que se conectam ao ecossistema de widgets do Jupyter foram sendo escritas
blz, resolvido

2021-10-14 20:16 UTC, marimeireles commented
>Uma última adição está no próprio ipywidgets: o novo widgetOutput pode exibir qualquer conteúdo que pode ser renderizado em um Jupyter notebook. Isso significa que qualquer coisa que você pode mostrar em um notebook, pode incluir em um widget usando apenas Python.

retirar

2021-10-15 10:04 UTC, laysauchoa commented
@marimeireles pode revisar? ^^ removed.

2021-10-16 10:11 UTC, merged