Marcos traducao 4,5,6
marimeireles/tutorial pull request #12
Opened 2021-10-14 20:24 UTC by Marcosap19

Revisem minha tradução

2021-10-16 22:52 UTC, marimeireles requested changes
nu, eh mt conteudo
valeu Marcos! <3
ficou mt bom mesmo, eu sinto q seus notebooks foram localizados de vdd, os meus ficaram bem mais paia a traducao :p
alguns comentarios, mas nada mt relevante. muito obrigada!
e... agora eh so so tirar as partes em ingles, eu diria. :)

2021-10-16 22:52 UTC, marimeireles commented on notebooks/04.WidgetList/04.01-more-on-output-widget.ipynb
> +    "Um output enriquecido também pode ser direcionado para a área de output. Qualquer coisa que é mostrada normalmente num notebook do Jupyter também irá ser mostrada normalmente no widget `Output`.
Nao sei se a gente traduz rich output, acho q eh um slang de computacao... mas tb, isso eh nitpicking. particularmente, eu nao traduziria, mas nao tenho certeza
se voce explicar o q eh um output enriquecido, nao faz diferenca

2021-10-16 22:52 UTC, marimeireles commented on notebooks/04.WidgetList/04.01-more-on-output-widget.ipynb
> +    "O widget de sidecar também vem com decoradot de captura, tal qual o de output."
decoradot = decorador

2021-10-16 22:52 UTC, marimeireles commented on notebooks/06.Layout/06.00-Layout-and-Styling-Overview.ipynb
> +    "+ [Layout e estilização dos labels de widgets (?)](06.11-OPTIONAL-widget-label-styling.ipynb) (por favor leia isto individualmente)."
eu diria pra adicionar um comentario falando q so ta disponivel em ingles e colocar esse link: https://github.com/jupyter-widgets/tutorial/blob/master/notebooks/06.Layout/06.11-OPTIONAL-widget-label-styling.ipynb
Mas assim, sla pode retirar tb, o q vc achar melhor.

2021-10-17 01:10 UTC, Marcosap19 commented
Apaguei as partes em inglês  e umas pequenas correções :)

2021-10-17 12:29 UTC, marimeireles commented
hmmm de onde vem esses conflitos I wonder
I will try to fix it locally
mas obrigada por remover as strings em ingles marcos :) :sun_with_face:

2021-10-17 12:50 UTC, merged

2021-10-17 12:50 UTC, marimeireles commented
AH scheisse esqueci de limpar os note