laysa/translation: eng to pt-br part 02
marimeireles/tutorial pull request #5
Opened 2021-10-01 12:43 UTC by laysauchoa

Part 02:

Alguns pontos:

* Esses exemplos nao rodaram:
````
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np

def f(m, b):
    plt.figure(2)
    plt.clf()
    plt.grid()
    x = np.linspace(-10, 10, num=1000)
    plt.plot(x, m * x + b)
    plt.ylim(-5, 5)
    plt.show() 
````
    
```
def plot_f(k, p):
    plt.figure(5)
    plt.clf()
    plt.grid()
    x = np.linspace(0, 4 * np.pi)
    y = np.sin(k*x - p)
    plt.plot(x, y)
    plt.show()
````

Sera que roda na sua maquina? ^^

2021-10-11 18:04 UTC, marimeireles requested changes
thank you once moreee :cherry_blossom:

2021-10-11 18:04 UTC, marimeireles commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "`interact` também pode ser usado como um decorador. Isso permite definir uma função e interagir com ela em uma única cena. Como este exemplo mostra, `interagir` também funciona com funções que p
como um decorator (pq eh o nome do conceito, nao acho q devamos traduzir)

2021-10-11 18:04 UTC, marimeireles commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "Quando você passa um `keyword argument` com valor inteiro de `10` (`x = 10`) para `interagir`, ele gera um `slider` com valor inteiro com um intervalo de `[-10, + 3 * 10]`. Neste caso, `10` é um
aqui o interact, nao deve ser traduzido
ou eu to viajando :question:

2021-10-11 18:04 UTC, marimeireles commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "reverse('Oi, pessoal!')"
Eu lembro que isso tava dando problema pq o original era hello world. voce trocou pra oi pessoal :grey_question:  sry eu nao sei cade o interrogacao nesse teclado pt

2021-10-11 18:04 UTC, marimeireles commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "Os `Dropdown menus` são construídos passando uma lista de strings. Nesse caso, as strings são usadas como nomes na IU do menu suspenso e passadas para a função Python subjacente."
Nesse caso, as strings são ambas usadas como nome no menu dropdown e passadas para a função Python que vem a seguir.

2021-10-11 18:04 UTC, marimeireles commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "Embora os exemplos até agora neste notebook tenham um output muito básica. Você pode ter possibilidades mais interessantes.\n",
muito básico. Você pode criar coisas mais interessatens.

2021-10-11 18:04 UTC, marimeireles commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "Por exemplo, a função abaixo plota uma linha reta cuja inclinação e interceptação são dados por seus argumentos."
são dadas

2021-10-11 18:04 UTC, marimeireles commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "# Mais Informações\n",
só um reminder de falar pro povo q isso ta em ingles e no repositorio original, e q traducoes pra expandir isso aqui sao bem vindas, por exemplo

2021-10-12 05:44 UTC, laysauchoa commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "Quando você passa um `keyword argument` com valor inteiro de `10` (`x = 10`) para `interagir`, ele gera um `slider` com valor inteiro com um intervalo de `[-10, + 3 * 10]`. Neste caso, `10` é um
ta certa :D

2021-10-12 05:45 UTC, laysauchoa commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "reverse('Oi, pessoal!')"
mt obrigada por ter lembrado. Eu troquei nos dois. to adorando esses pontos de interrogacao :grey_question: :question:

2021-10-12 05:45 UTC, laysauchoa commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "# Mais Informações\n",
coloquei um comentario assim nao esqueco :)

2021-10-12 05:45 UTC, laysauchoa commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "Embora os exemplos até agora neste notebook tenham um output muito básica. Você pode ter possibilidades mais interessantes.\n",
vlw

2021-10-12 05:46 UTC, laysauchoa commented on notebooks/02.Interact/02.00-Using-Interact.ipynb
> +    "Os `Dropdown menus` são construídos passando uma lista de strings. Nesse caso, as strings são usadas como nomes na IU do menu suspenso e passadas para a função Python subjacente."
resolvido

2021-10-15 10:07 UTC, laysauchoa commented
@marimeireles good to go :)

2021-10-16 10:04 UTC, merged