laysa/translation: eng to pt-br part 00_index
marimeireles/tutorial pull request #9
Opened 2021-10-04 15:20 UTC by laysauchoa

P.S.: adicionei o github de voces como agradecimento e emojis.

2021-10-11 17:50 UTC, marimeireles requested changes
thaaankz :rabbit:

2021-10-11 17:50 UTC, marimeireles commented on notebooks/00.00-index.ipynb
> +    "Agradecimentos pela adaptação para o português: \n",
Diria q seu nome vai primeiro, depois marcos depois o meu, por ordem alfabetica =)

2021-10-11 17:50 UTC, marimeireles commented on notebooks/00.00-index.ipynb
> +    "+ Agradecimentos especiais às dezenas de [desenvolvedores de ipywidgets](https://github.com/jupyter-widgets/ipywidgets/graphs/contributors), incluindo Jonathan Frederic, que escreveu grande part
Diria q c nao precisa agradecer ninguem na apresentacao, tipo falar os nomes das pessoas, pode pular isso... soaria mt estranho pra mim (pessoalmente, e a galera nao fez isso no scypy tb nao)

2021-10-12 07:38 UTC, laysauchoa commented on notebooks/00.00-index.ipynb
> +    "+ Agradecimentos especiais às dezenas de [desenvolvedores de ipywidgets](https://github.com/jupyter-widgets/ipywidgets/graphs/contributors), incluindo Jonathan Frederic, que escreveu grande part
Ah, sim! Irei apenas comentar que o projeto original era em ingles e tals e que traduzimos e convidar para continuar traduzindo, o que achas?

2021-10-12 07:40 UTC, laysauchoa commented on notebooks/00.00-index.ipynb
> +    "Agradecimentos pela adaptação para o português: \n",
faz sentido! corrigido :)

2021-10-14 20:17 UTC, marimeireles commented on notebooks/00.00-index.ipynb
> +    "+ Agradecimentos especiais às dezenas de [desenvolvedores de ipywidgets](https://github.com/jupyter-widgets/ipywidgets/graphs/contributors), incluindo Jonathan Frederic, que escreveu grande part
sim

2021-10-15 10:05 UTC, laysauchoa commented
@marimeireles ready for final review ;)

2021-10-16 10:06 UTC, merged